### ISSUE TITLE
Add the AddinCLientService throws an error

### ISSUE THREAD

**Issue by gilsondia** [blackbaud/skyux-lib-addin-client#44]
I cannot find any documentation or support for that, any help would be good.

Error below:

Uncaught TypeError: Cannot read properties of undefined (reading 'Injectable')
    at Module../node_modules/@blackbaud/skyux-lib-addin-client/fesm2015/blackbaud-skyux-lib-addin-client.js (app.module.ts:36:23)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module../src/app/home.component.ts (app-nav.component.ts:10:29)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module../node_modules/@skyux-sdk/builder/src/app/sky-pages.module.ts (skyux-config.js:286:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module../node_modules/@skyux-sdk/builder/src/app/app.module.ts (skyux-config.js:217:1)

**Comment by michael-tims** [comment]
This issue cannot be reproduce,  If you are still experiencing the error we can reopen and troubleshoot further.  Thanks!
